hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 15.0
translate: 0.15
scale: 0.5
shear: 5.0
perspective: 0.0001
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.15
copy_paste: 0.1
auto_augment: ""
erasing: 0.4
crop_fraction: 1.0
